name: 'Deploy App Workflow'
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      branch:
        required: true
        type: string
    secrets:
      app_env:
        required: true
      vercel_token:
        required: true
      org_id:
        required: true
      project_id:
        required: true

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      # TODO set deployment url
      # url:
    concurrency:
      cancel-in-progress: true
      group: ${{ inputs.environment }}
    env:
      VERCEL_ORG_ID: ${{ secrets.org_id }}
      VERCEL_PROJECT_ID: ${{ secrets.project_id }}
    steps:
      - name: Checkout ${{ inputs.branch }} branch
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.1

      - uses: actions/setup-node@v2
        with:
          node-version: 16.15.0
          cache: 'pnpm'

      - name: Set node environment variables
        run: echo ${{ secrets.app_env }} | openssl base64 -d -A -out .env

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Vercel CLI
        run: pnpm add vercel@latest

      - name: Vercel Build
        run: |
          environment=""
          prodRun=""

          if [[ "${{ inputs.environment }}" == "production" ]]
          then
            environment="--environment=production"
            prodRun="--prod"
          elif [[ "${{ contains(inputs.branch, 'develop') }}" == "false" ]]
          then
            environment="--environment=preview"
          fi

          echo environment: $environment
          echo prodRun: $prodRun

          vercel pull --yes $environment --token=${{ secrets.vercel_token }}
          vercel build $prodRun --token=${{ secrets.vercel_token }}
        # vercel deploy --prebuilt $prodRun --token=${{ secrets.vercel_token }}

      - uses: amondnet/vercel-action@v20
        name: Deploy to Vercel Preview
        id: vercel_preview
        if: contains(inputs.branch, 'develop') == false && inputs.environment == 'dev'
        with:
          vercel-token: ${{ secrets.vercel_token }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: 'deploy --prebuilt'
          vercel-org-id: ${{ secrets.org_id}}
          vercel-project-id: ${{ secrets.project_id}}
          working-directory: ./

      - uses: amondnet/vercel-action@v20
        name: Deploy to Vercel Develop
        id: vercel_develop
        if: contains(inputs.branch, 'develop')
        with:
          vercel-token: ${{ secrets.vercel_token }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: 'deploy --prebuilt'
          vercel-org-id: ${{ secrets.org_id}}
          vercel-project-id: ${{ secrets.project_id}}
          working-directory: ./
          alias-domains: |
            develop-t3-stack-app.vercel.app

      - uses: amondnet/vercel-action@v20
        name: Deploy to Vercel Production
        id: vercel_production
        if: inputs.environment == 'production'
        with:
          vercel-token: ${{ secrets.vercel_token }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: 'deploy --prebuilt --prod '
          vercel-org-id: ${{ secrets.org_id}}
          vercel-project-id: ${{ secrets.project_id}}
          working-directory: ./

      # - name: Set Vercel Deployment URL
      #   run: |
      #     url=""
      #     echo "::set-output name=vercel_url::http://$(pulumi stack output bucketUrl)"
