name: 'PR Tests'
on:
  pull_request:
    branches: [main, develop]

jobs:
  pr-lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.1

      - uses: actions/setup-node@v2
        with:
          node-version: 16.15.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set environment variables
        run: echo ${{ secrets.TEST_APP_ENV }} | openssl base64 -d -A -out .env

      - name: Run lint and type checks
        run: |
          pnpm concurrently -g \
          "pnpm lint" \
          "pnpm check:types"

  pr-deploy-preview:
    if: github.event.pull_request.base.ref == 'develop'
    needs: [pr-lint-and-test]
    uses: ./.github/workflows/deploy-action.yml
    with:
      environment: dev
      branch: ${{ github.ref }}
    secrets:
      app_env: ${{ secrets.APP_ENV }}
      vercel_token: ${{ secrets.VERCEL_TOKEN }}
      org_id: ${{ secrets.VERCEL_ORG_ID }}
      project_id: ${{ secrets.VERCEL_PROJECT_ID }}
